config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'auth#login'
  scope '/legal' do
    get '/terms' => 'public#terms', as: :terms
    get '/privacy' => 'public#privacy', as: :privacy
    get '/aup' => 'public#aup', as: :aup
  end
  scope '/federation' do
    get '/authorize' => "flow#prompt"
  end
  scope '/account' do
    get '/login' => 'auth#login', as: :login
    post '/login' => 'auth#build_user'
    get '/logout' => 'auth#logout'
    get '/signup' => 'auth#signup', as: :signup
    get '/forgot' => 'auth#reset', as: :reset
    get '/confirm/:email/:code' => 'auth#confirm', as: :confirm, :constraints => { email: /[^\/]+/  }
    get '/reset/:reset_code' => 'auth#password', as: :password
  end
  scope '/console' do
    get '/', to: redirect('/console/account')
    get '/account' => 'console#account', as: :account
    get '/log' => 'console#log', as: :log
    scope '/admin' do
      get '/users' => 'admin#users', as: :users
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :current_user
    before_action :current_session
    before_action :current_admin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cache_headers
  helper_method :gravatar_url
  before_action :render_time


  def render_time
    @start_time = Time.now
  end

  def current_user
    @current_user ||= JSON.parse(session[:user_json], symbolize_names: true) if session[:user_json]
  end

  def current_session
    redirect_to "/account/login?returl=#{CGI.escape(request.fullpath)}", :only_path => true unless @current_user
  end

  def current_admin
    redirect_to "/console/account" unless @current_user[:permission_level] == 0
  end

  def home_if_logged_in
    redirect_to "/console/account" if session[:user_json]
  end

  def gravatar_url(email, size)
    gravatar = Digest::MD5::hexdigest(email).downcase
    url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end

  def require_user
    redirect_to '/account/login' unless current_user
  end

  private

  def set_cache_headers
    response.headers['Cache-Control'] = 'no-cache, no-store'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = 'Fri, 01 Jan 1990 00:00:00 GMT'
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  before_action :home_if_logged_in, except: :logout
  def build_user
    session[:user_json] = request.raw_post
  end

  def logout
    reset_session
    redirect_to login_path
  end
end

app/controllers/console_controller.rb
class ConsoleController < ApplicationController
  before_action :current_user
  before_action :current_session
end

app/controllers/flow_controller.rb
class FlowController < ApplicationController
  before_action :current_user
  before_action :current_session

  layout "error"
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  before_action :current_user
end

app/controllers/saml_controller.rb
class SamlController < ApplicationController
  before_action :current_user
  before_action :current_session

  layout "error"
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar(email, size)
    gravatar_id = Digest::MD5.hexdigest(email)
    "https://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/console_helper.rb
module ConsoleHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/saml_helper.rb
module SamlHelper
end

app/views/admin/users.html.erb
<% content_for :console, 1 %>
<% content_for :loggedin, 1 %>
<% content_for :page_class, "teamWizard teamWizardDARK mobile js" %>
<section id="content"><a name="content"></a>
  <div id="PSBUTTONCONTAINER"></div>
  <div id="CONSOLE">
    <div data-reactroot="">
      <div class="tTop">
        <div style="display: flex;">
          <div style="display: flex;"><a href="/"><img src="<%= ENV['APP_BRAND_LOGO_LIGHT'] %>" class="miniLogo" style="cursor: pointer;"></a></div><br></div>
        <div class="tHeader">
          <h1><!-- react-text: 10 --><sup>[ADMIN]</sup> Console<!-- /react-text --><!-- react-text: 11 --> <!-- /react-text --><span class="subTitle"></span></h1></div>
          <div id="PSBUTTON" class="noselect loaded">
            <div class="accountName bold"><span class=""><% if ((@current_user[:first_name].present?) && (@current_user[:last_name].present?)) %><%= @current_user[:first_name] %> <%= @current_user[:last_name] %><% else %><%= @current_user[:email] %><% end %></span></div>
            <div class="gravContainer"><%= image_tag gravatar(@current_user[:email], 200), :class => "gravatarImg2" %></div>
            <div class="psmenu">
              <ul role="menu" class="dropdown-menu profile-dropdown" style="position: relative;">
                <% if @current_user[:permission_level] <= 2 %>
                <li style="margin-top: 0px;"><a href="<%= users_path %>" class="clearfix" style="cursor: pointer;"><span class="pull-left"><i class="fa fa-shield"></i></span><span class="m-l-5">Administration</span></a></li>
                <% end %>
                <li style="margin-top: 0px;" id="logoutButton"><a class="clearfix" style="cursor: pointer;"><span class="pull-left"><i class="pg-power"></i></span><span class="m-l-5">Logout</span></a></li>

              </ul>
            </div>
          </div>
      </div>
      <div style="margin: auto; max-width: 900px; padding: 0px 30px 30px;">
        <div class="tMenu">
          <div class="tMenuEntry"><a class="alt-font" href="/console/account"><span>&larr; Home</span></a></div>
          <div class="tMenuEntry"><a class="alt-font selected" href="/console/admin/users"><span>Users</span></a></div>
        </div>
        <div class="row">
          <div class="col-md-12 tContent"><span></span>
            <div>
              <div>
                <div>
                  <div class="row m-t-15">
                    <div class="col-sm-12 m-b-15" style="min-height: 2em;"><span></span></div>
                    <div class="col-sm-12">
                      <table class="table machineTable" data-sort="table" style="backface-visibility: hidden;">
                        <thead>
                          <tr>
                            <th class="headerTable">Name</th>
                            <th class="headerTable">Email</th>
                            <th class="headerTable">Date Signed Up</th>
                            <th class="headerTable">Verified Email</th>
                            <th class="headerTable">Enabled</th>
                            <th class="headerTable">2FA Enabled</th>
                            <th class="headerTable">Admin</th>
                            <th class="headerTable">Actions</th>
                          </tr>
                        </thead>
                        <tbody id="tableBody">
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12" id="react-paginate">
                      <ul class="pagination">
                        <li class="previous disabled"><a>previous</a></li>
                        <li class="next disabled"><a>next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div><br><br><br></div>
          </div>
        </div>
        <div class="mapcontainer "></div>
      </div>
    </div>
</section>
<script>
function strftime(sFormat, date) {
  if (!(date instanceof Date)) date = new Date();
  var nDay = date.getDay(),
    nDate = date.getDate(),
    nMonth = date.getMonth(),
    nYear = date.getFullYear(),
    nHour = date.getHours(),
    aDays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    aMonths = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    aDayCount = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334],
    isLeapYear = function() {
      if ((nYear&3)!==0) return false;
      return nYear%100!==0 || nYear%400===0;
    },
    getThursday = function() {
      var target = new Date(date);
      target.setDate(nDate - ((nDay+6)%7) + 3);
      return target;
    },
    zeroPad = function(nNum, nPad) {
      return ('' + (Math.pow(10, nPad) + nNum)).slice(1);
    };
  return sFormat.replace(/%[a-z]/gi, function(sMatch) {
    return {
      '%a': aDays[nDay].slice(0,3),
      '%A': aDays[nDay],
      '%b': aMonths[nMonth].slice(0,3),
      '%B': aMonths[nMonth],
      '%c': date.toUTCString(),
      '%C': Math.floor(nYear/100),
      '%d': zeroPad(nDate, 2),
      '%e': nDate,
      '%F': date.toISOString().slice(0,10),
      '%G': getThursday().getFullYear(),
      '%g': ('' + getThursday().getFullYear()).slice(2),
      '%H': zeroPad(nHour, 2),
      '%I': zeroPad((nHour+11)%12 + 1, 2),
      '%j': zeroPad(aDayCount[nMonth] + nDate + ((nMonth>1 && isLeapYear()) ? 1 : 0), 3),
      '%k': '' + nHour,
      '%l': (nHour+11)%12 + 1,
      '%m': zeroPad(nMonth + 1, 2),
      '%M': zeroPad(date.getMinutes(), 2),
      '%p': (nHour<12) ? 'AM' : 'PM',
      '%P': (nHour<12) ? 'am' : 'pm',
      '%s': Math.round(date.getTime()/1000),
      '%S': zeroPad(date.getSeconds(), 2),
      '%u': nDay || 7,
      '%V': (function() {
              var target = getThursday(),
                n1stThu = target.valueOf();
              target.setMonth(0, 1);
              var nJan1 = target.getDay();
              if (nJan1!==4) target.setMonth(0, 1 + ((4-nJan1)+7)%7);
              return zeroPad(1 + Math.ceil((n1stThu-target)/604800000), 2);
            })(),
      '%w': '' + nDay,
      '%x': date.toLocaleDateString(),
      '%X': date.toLocaleTimeString(),
      '%y': ('' + nYear).slice(2),
      '%Y': nYear,
      '%z': date.toTimeString().replace(/.+GMT([+-]\d+).+/, '$1'),
      '%Z': date.toTimeString().replace(/.+\((.+?)\)$/, '$1')
    }[sMatch] || sMatch;
  });
}

$.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin',
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function (data) {
      $.each(data.users, function(i, item){
        if(data.users[i].first_name == null) {
          var name = "&lt;not set&gt;";
        } else {
          var name = data.users[i].first_name + ' ' + data.users[i].last_name;
        }
        if(data.users[i].shell_username == null){
          var shell_username = "&lt;not set&gt;";
        } else {
          var shell_username = data.users[i].shell_username;
        }
        if(data.users[i].activated == false){
          var active = "No";
        } else {
          var active = "Yes";
        }
        if(data.users[i].active == false){
          var enabled = "<a title='Enable user' class='enableUser' style='cursor: pointer;'>No</a>";
        } else {
          var enabled = "<a title='Disable user' class='disableUser' style='cursor: pointer;'>Yes</a>";
        }
        if(data.users[i].tfa_enabled == false){
          var tfa = "No";
        } else {
          var tfa = "<a title='Disable 2FA' class='disable2FA' style='cursor: pointer;'>Yes</a>";
        }
        if(data.users[i].permission_level == 99){
          var admin = "<a title='Make admin' class='makeAdmin' style='cursor: pointer;'>No</a>";
        } else {
          var admin = "<a title='Make user' class='makeUser' style='cursor: pointer;'>Yes</a>";
        }
    
        var msg = '<tr class="usrlst"> \
          <td class="bodyTable">'+name+'</td> \
          <td class="bodyTable emailSelect">'+data.users[i].email+'</td> \
          <td class="bodyTable">'+strftime("%d/%m/%Y at %l:%M%P", new Date(data.users[i].created_at))+'</td> \
          <td class="bodyTable">'+active+'</td> \
          <td class="bodyTable">'+enabled+'</td> \
          <td class="bodyTable">'+tfa+'</td> \
          <td class="bodyTable">'+admin+'</td> \
          <td class="bodyTable"><a class="dropUser" style="cursor: pointer;">Drop</a></td>\
        </tr>';
        $('#tableBody').append(msg)
      })
    }
})

$(document).on('click', '.enableUser', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/enable/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Disable user' class='disableUser' style='cursor: pointer;'>Yes</a>");
      }
    }
  })
})

$(document).on('click', '.disableUser', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/disable/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Enable user' class='enableUser' style='cursor: pointer;'>No</a>");
      }
    }
  })
})

$(document).on('click', '.enableSaml', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/saml/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Disable SAML Login' class='disableSaml' style='cursor: pointer;'>Yes</a>");
      }
    }
  })
})

$(document).on('click', '.disableSaml', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/nosaml/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Enable SAML Login' class='enableSaml' style='cursor: pointer;'>No</a>");
      }
    }
  })
})

$(document).on('click', '.makeAdmin', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/admin/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Make user' class='makeUser' style='cursor: pointer;'>Yes</a>");
      }
    }
  })
})
$(document).on('click', '.makeUser', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/user/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("<a title='Make admin' class='makeAdmin' style='cursor: pointer;'>No</a>");
      }
    }
  })
})
$(document).on('click', '.dropUser', function(e) {
  e.preventDefault()
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/delete/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
        $(prop).parent().parent().remove()
    }
  })
})
$(document).on('click', '.disable2FA', function(e) {
  e.preventDefault();
  var email = $(this).parent().parent().find(".bodyTable.emailSelect").html()
  var prop = this

  $.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/admin/2fa/'+email,
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function(data) {
      if(data.user_updated == true){
        $(prop).parent().html("No");
      }
    }
  })
})
  </script>

app/views/console/log.html.erb
<% content_for :console, 1 %>
<% content_for :loggedin, 1 %>
<% content_for :logs, 1 %>
<% content_for :page_class, "teamWizard teamWizardDARK mobile js" %>
<section id="content"><a name="content"></a>
  <div id="PSBUTTONCONTAINER"></div>
  <div id="CONSOLE">
    <div data-reactroot="">
      <div class="tTop">
        <div style="display: flex;">
          <div style="display: flex;"><a href="/"><img src="<%= ENV['APP_BRAND_LOGO_LIGHT'] %>" class="miniLogo" style="cursor: pointer;"></a></div><br></div>
        <div class="tHeader">
          <h1><!-- react-text: 10 -->Console<!-- /react-text --><!-- react-text: 11 --> <!-- /react-text --><span class="subTitle"></span></h1></div>
          <div id="PSBUTTON" class="noselect loaded">
            <div class="accountName bold"><span class=""><% if ((@current_user[:first_name].present?) && (@current_user[:last_name].present?)) %><%= @current_user[:first_name] %> <%= @current_user[:last_name] %><% else %><%= @current_user[:email] %><% end %></span></div>
            <div class="gravContainer"><%= image_tag gravatar(@current_user[:email], 200), :class => "gravatarImg2" %></div>
            <div class="psmenu">
              <ul role="menu" class="dropdown-menu profile-dropdown" style="position: relative;">
                <% if @current_user[:permission_level] <= 2 %>
                <li style="margin-top: 0px;"><a href="<%= users_path %>" class="clearfix" style="cursor: pointer;"><span class="pull-left"><i class="fa fa-shield"></i></span><span class="m-l-5">Administration</span></a></li>
                <% end %>
                <li style="margin-top: 0px;" id="logoutButton"><a class="clearfix" style="cursor: pointer;"><span class="pull-left"><i class="pg-power"></i></span><span class="m-l-5">Logout</span></a></li>

              </ul>
            </div>
          </div>
      </div>
      <div style="margin: auto; max-width: 900px; padding: 0px 30px 30px;">
      <%= render 'partials/layout/console_menu' %>
        <div class="row">
          <div class="col-md-12 tContent"><span></span>
            <div>
              <div>
                <div>
                  <div class="row m-t-15">
                    <div class="col-sm-12 m-b-15" style="min-height: 2em;"><span></span></div>
                    <div class="col-sm-12">
                      <table class="table machineTable" data-sort="table" style="backface-visibility: hidden;">
                        <thead>
                          <tr>
                            <th class="headerTable">Action performed by</th>
                            <th class="headerTable" style="text-align: center;">Action performed</th>
                            <th class="headerTable">Date logged</th>
                          </tr>
                        </thead>
                        <tbody id="tableBody">
                        </tbody>
                      </table>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-sm-12" id="react-paginate">
                      <ul class="pagination">
                        <li class="previous disabled"><a>previous</a></li>
                        <li class="next disabled"><a>next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div><br><br><br></div>
          </div>
        </div>
        <div class="mapcontainer "></div>
      </div>
    </div>
</section>
<script>
function strftime(sFormat, date) {
  if (!(date instanceof Date)) date = new Date();
  var nDay = date.getDay(),
    nDate = date.getDate(),
    nMonth = date.getMonth(),
    nYear = date.getFullYear(),
    nHour = date.getHours(),
    aDays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    aMonths = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    aDayCount = [0, 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334],
    isLeapYear = function() {
      if ((nYear&3)!==0) return false;
      return nYear%100!==0 || nYear%400===0;
    },
    getThursday = function() {
      var target = new Date(date);
      target.setDate(nDate - ((nDay+6)%7) + 3);
      return target;
    },
    zeroPad = function(nNum, nPad) {
      return ('' + (Math.pow(10, nPad) + nNum)).slice(1);
    };
  return sFormat.replace(/%[a-z]/gi, function(sMatch) {
    return {
      '%a': aDays[nDay].slice(0,3),
      '%A': aDays[nDay],
      '%b': aMonths[nMonth].slice(0,3),
      '%B': aMonths[nMonth],
      '%c': date.toUTCString(),
      '%C': Math.floor(nYear/100),
      '%d': zeroPad(nDate, 2),
      '%e': nDate,
      '%F': date.toISOString().slice(0,10),
      '%G': getThursday().getFullYear(),
      '%g': ('' + getThursday().getFullYear()).slice(2),
      '%H': zeroPad(nHour, 2),
      '%I': zeroPad((nHour+11)%12 + 1, 2),
      '%j': zeroPad(aDayCount[nMonth] + nDate + ((nMonth>1 && isLeapYear()) ? 1 : 0), 3),
      '%k': '' + nHour,
      '%l': (nHour+11)%12 + 1,
      '%m': zeroPad(nMonth + 1, 2),
      '%M': zeroPad(date.getMinutes(), 2),
      '%p': (nHour<12) ? 'AM' : 'PM',
      '%P': (nHour<12) ? 'am' : 'pm',
      '%s': Math.round(date.getTime()/1000),
      '%S': zeroPad(date.getSeconds(), 2),
      '%u': nDay || 7,
      '%V': (function() {
              var target = getThursday(),
                n1stThu = target.valueOf();
              target.setMonth(0, 1);
              var nJan1 = target.getDay();
              if (nJan1!==4) target.setMonth(0, 1 + ((4-nJan1)+7)%7);
              return zeroPad(1 + Math.ceil((n1stThu-target)/604800000), 2);
            })(),
      '%w': '' + nDay,
      '%x': date.toLocaleDateString(),
      '%X': date.toLocaleTimeString(),
      '%y': ('' + nYear).slice(2),
      '%Y': nYear,
      '%z': date.toTimeString().replace(/.+GMT([+-]\d+).+/, '$1'),
      '%Z': date.toTimeString().replace(/.+\((.+?)\)$/, '$1')
    }[sMatch] || sMatch;
  });
}
$.ajax({
    type: 'GET',
    url: '<%= ENV['IDENTITY_API_PROTOCOL'] %>://<%= ENV['IDENTITY_API_URL'] %>/api/v1/logs',
    headers: {
        "Authorization": "Bearer <%= @current_user[:api_key] %>"
    },
    success: function (data) {
        $.each(data["logs"], function (i, item) {
            console.log("DEBUG: Processing message " + i);
            var user = "Me";
            if (data["logs"][i].administrative == true) {
                var user = "Staff Account";
            }

            var msg = '<tr class="usrlst"> \
        <td class="bodyTable">' + user + '</td> \
        <td class="bodyTable" style="text-align: center;">' + data["logs"][i].action + '</td> \
        <td class="bodyTable">' + strftime("%d/%m/%Y at %l:%M%P", new Date(data["logs"][i].created_at)) + '</td> \
      </tr>';
            $('#tableBody').append(msg)
        });
    }
});

  </script>

app/views/layouts/application.html.erb
<%= render 'partials/layout/head' %>
		<% if((content_for?(:login)) || (yield(:page_class) == "undefined signup")) %>
		<script>
		document.cookie = 'token=;expires=Thu, 01 Jan 1970 00:00:01 GMT;';
		</script>
		<% end %>
	<%= render 'partials/layout/body_top' %>
	<%= yield %>
	<% if yield(:page_class) == "undefined signup" %>
		<%= render 'partials/footer/footer_account' %>
	<% end %>
	<%= render 'partials/footer/footer' %>
</body>
</html>

app/views/layouts/error.html.erb
<%= render 'partials/layout/head' %>
	<%= render 'partials/layout/body_top' %>
	<%= yield %>
</body>
</html>

app/views/partials/footer/_footer.html.erb
<footer id="footer">
  <div class="logo small"><a href="/">The <%= ENV['APP_SHORT_COMPANY_NAME'] %> Network</a></div>
  <nav id="footerNav">
    <ul>
      <li class="sections">
        <ul>
          <li class="topLI"><span class="alt-font">Resources</span></li>
          <li><%= link_to "Terms of Use", terms_path, :class => "alt-font" %></li>
          <li><%= link_to "Privacy Policy", privacy_path, :class => "alt-font" %></li>
          <li><%= link_to "Acceptable Use Policy", aup_path, :class => "alt-font" %></li>

        </ul>
      </li>
  </nav>
    <div class="bottompart">
    <div class="copyright alt-font">&copy; 2019 <%= ENV['APP_COMPANY_NAME'] %> | <%= ENV['APP_BRAND_STRING'] %> Version <%= Time.now.strftime("%Y%m%d") %></div>
    <div class="pshq"><i class="icon icon_pin"></i> <%= ENV['APP_COUNTRY_STRING'] %></div>
  </div>
  <a href="#top" class="slide-round">
    <div class="overflow"><svg viewbox="0 0 56 56" style="enable-background:new 0 0 56 56;" xml:space="preserve" class="off"><polygon points="23.5,28.2 31.3,36 32,35.3 24.2,27.5 32,19.7 31.3,19 23.5,26.8 22.8,27.5"></polygon></svg><svg viewbox="0 0 56 56" style="enable-background:new 0 0 56 56;"
        xml:space="preserve" class="on"><polygon points="23.5,28.2 31.3,36 32,35.3 24.2,27.5 32,19.7 31.3,19 23.5,26.8 22.8,27.5"></polygon></svg></div>
  </a>
  <div class="clearfix"></div>
</footer>
<div id="overlay"></div>
<link href="https://ltscdn.m6.nz/shell/main/stylesheets/ant.rate.css" rel="stylesheet">
</div>
</body>
</html>

app/views/partials/footer/_footer_account.html.erb
<footer id="footer">
  <div class="container">
    <nav class="nav">
      <ul>
      <li style="visibility: hidden"><a href="javascript:void(0)"><span class="innerSpinner"></span>Blank Space</a></li>
      <li><a href="/legal/terms"><span class="innerSpinner"></span>Terms of Use</a></li>
      <li><a href="/legal/privacy"><span class="innerSpinner"></span>Privacy Policy</a></li>
      <li style="visibility: hidden"><a href="javascript:void(0)"><span class="innerSpinner"></span>Blank Space</a></li>
      </ul>
    </nav>
  </div>
</footer>
<div id="overlay"></div>
</div>